export const FETCH_USER = 'FETCH_USER';
export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_SHOPPING_ITEMS = 'FETCH_SHOPPING_ITEMS';
export const CREATE_SHOPPING_ITEM = 'CREATE_SHOPPING_ITEM';
export const UPDATE_SHOPPING_ITEM_CHECKED = 'UPDATE_SHOPPING_ITEM_CHECKED';
export const DELETE_SHOPPING_ITEMS = 'DELETE_SHOPPING_ITEMS';
